name: Deploy Frontend

on:
  push:
    branches: [main]

env:
  PROJECT_DIR: 2025_PhyoNyiNyiPaing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/coin-react-frontend .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/coin-react-frontend

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run Ansible to deploy
        run: |
          ansible-playbook playbook.yml -i ${{ secrets.EC2_HOST }}, -u ${{ secrets.EC2_USER }} --ssh-extra-args "-o StrictHostKeyChecking=no"
